- NEWS
- bin/xbps-create/main.c
- bin/xbps-rindex/index-add.c
- data/_xbps
- data/xbps.bash
- doc/xbps_pkg_props_dictionary.dot
Removes the build-date property as discussed in #110. closes #110.
> xbps-create: do not add a build-date property to packages.

- NEWS
- bin/xbps-query/main.c
Currently if a user missused the xbps-query commando it's able to silently print the wrong results, e.g.:
```
xbps-query -s -R foobar
```
This command searches for the string "-R" and completely ignores the foobar at the end. This changes will let the command fail if there are trailing arguments.
> xbps-query: fail on trailing parameters.

- lib/pkgdb.c
This commit adds setting the process umask to 0664 prior to opening/creating so that pkgdb remains readable for world, even if xbps tools have been called with a very restrictive umask (like through sudo by a user with a umask 0700).
Maybe this behavior should be settable through a configuration option or a environment variable.
> set umask for pkgdb creation/access 

- bin/xbps-checkvers/main.c
- tests/xbps/xbps-checkvers/checkvers.sh
The debug printing is also moved after variable substitution.
Now it prints:
foo/template: _var foo
foo/template: pkgname foo
It used to print:
foo/template: _var foo
foo/template: pkgname ${_var}
> Fix #120 by stripping comments from the end of lines.

- lib/package_alternatives.c
- tests/xbps/xbps-alternatives/main.sh
This commit adds relative link support to lib/package_alternatives.c. Instead of creating absolute links, xbps will create relative links to the target. This allows to follow links on systems even if the aren't mounted on /.
> lib/package_alternatives.c: always use relative symlinks in alternatives

- CONTRIBUTORS
- bin/xbps-create/main.c
- bin/xbps-rindex/repoflush.c
- configure
- lib/fetch/common.c
- lib/initend.c
- lib/package_alternatives.c
- lib/package_script.c
Fixes the build on FreeBSD (10.3+ only atm, earlier versions are missing
futimens/utimensat and need some more work).
This actually passes the testsuite, but the testsuite needs some adjustments
for differing output/behaviour of `sed`,`wc` and `errno` values. See 
my [freebsd-tests](/ebfe/xbps/tree/freebsd-tests) branch
> freebsd build

- bin/xbps-query/search.c
Otherwise clang will complain with the following message:
```
search.c:67:3: error: variable 'i' is incremented both in the loop
header and in the loop body [-Werror,-Wfor-loop-analysis]
```
> xbps-query: remove doubled incrementation

- NEWS
- bin/xbps-rindex/defs.h
- bin/xbps-rindex/index-add.c
- bin/xbps-rindex/index-clean.c
- bin/xbps-rindex/remove-obsoletes.c
- bin/xbps-rindex/repoflush.c
- bin/xbps-rindex/sign.c
- include/xbps.h.in
- lib/repo.c
- tests/xbps/xbps-rindex/Kyuafile
- tests/xbps/xbps-rindex/Makefile
- tests/xbps/xbps-rindex/add_test.sh
- tests/xbps/xbps-rindex/clean_test.sh
- tests/xbps/xbps-rindex/remove_test.sh
When adding packages to the index, xbps-rindex will check if the
consistency of shlibs is broken by a package. If so, rindex will create
a stage file and commit the packages there. Once the consistency
is restored, rindex -a will commit the stage area back to the public
repo and delete the stage file.
TODO:
* ...is correctly added to the stage area
* ...is correctly removed from the stage area when the inconsistency is gone
> xbps-rindex: check for consistent shlibs

- lib/portableproplib/prop_object.c
- lib/portableproplib/prop_object_impl.h
Applies the following patches from NetBSD:
http://cvsweb.netbsd.org/bsdweb.cgi/src/common/lib/libprop/prop_object.c?rev=1.30&content-type=text/x-cvsweb-markup
http://cvsweb.netbsd.org/bsdweb.cgi/src/common/lib/libprop/prop_object_impl.h?rev=1.31.12.1&content-type=text/x-cvsweb-markup
> lib/portableproplib: fix various oob reads/segfaults

- bin/xbps-create/main.c
xbps-create uses nftw(3) to walk through all files. As nftw doesn't
sort files it may happen that the resulting packages will have
different checksums due to differentiating orders of files in the tar-file.
To solve this issue xbps-create moves from simple lists to xbps_directory_t, which is always
sorted.
Please note, that this is only tested using the kyua testing framework.
> Reproducible create

- lib/pubkey2fp.c
Calling EVP_cleanup here undoes initialization already done in lib/fetch
ssl_init causing subsequent attempts to call SSL_CTX_new() to fail.
Which ultimately is the root cause for #170.
Fixes #170 
Maybe moving all LibreSSL initialization/cleanup stuff into xbps_init/end is a good idea?
> lib: dont call EVP_cleanup in fp2str

- NEWS
- bin/xbps-create/main.c
- include/xbps.h.in
- lib/util_hash.c
- lib/verifysig.c
fixes #182
I left mmap for the *.sig files in which I consider safe.
> Avoid mmap

- lib/fetch/common.c
- lib/fetch/common.h
- lib/fetch/fetch.c
- lib/fetch/fetch.h
This adds support for socks5 proxies using a SOCKS_PROXY environment variable.
`SOCKS_PROXY="socks5://[user:pass@]127.0.0.1:9050"`
> lib/fetch: add socks5 support

- bin/xbps-install/transaction.c
`xbps-install` will report free space available on disk wording:
> Free space on disk: ...
'free' above is supposed to be  an adjective.
But 'free' can also be a verb,
thus the above message can be interpreted as free some space on disk.
'Free' is now changed to 'Available' to avoid ambiguity.
---
bin/xbps-install/transaction.c | 2 +-
1 file changed, 1 insertion(+), 1 deletion(-)
> Change free space message to avoid ambiguity.

- bin/xbps-remove/clean-cache.c
- bin/xbps-remove/defs.h
- bin/xbps-remove/main.c
`xbps-remove --clean-cache --dry-run` did not consider the
--dry-run flag, this has been fixed.
Fixes #165.
> xbps-remove: fix --dry-run for --clean-cache

- bin/xbps-install/fetch_cb.c
stdout is buffered and the automatic flush on '\n' seems to only work when
stdout isatty() in which case we take the other branch. This fixes the
delayed/buffered progress updates in xbps-src fetch ...
> bin/xbps-install/fetch_cb.c: flush stdout when printing progress

- bin/xbps-checkvers/xbps-checkvers.1
unless ... not set <=> except if (... not set), which makes no sense here.
> xbps-checkvers.1: fix incorrect double negative

- bin/xbps-uchroot/main.c
This should fix the issue mentioned by @ebfe in #152.
I'm not sure if there should be error checks or maybe a more smart way to umount relative paths and chroot to avoid all the snprintf calls.
> xbps-uchroot: umount chroot mounts

- bin/xbps-rindex/index-add.c
- lib/package_configure.c
- lib/package_unpack.c
- lib/transaction_shlibs.c
This fixes a few memory leaks I found by running xbps-\* commands in the test suite with valgrind.
There are a few more but they are not that easy to fix, I added two comments where I tried to fix it but failed because it uses the values in some other functions and therefor segfaults later if its freed.
```
sed -i -e 's|xbps-|valgrind --leak-check=full --track-origins=yes --log-file=/home/duncan/repos/xbps/logs/%p.log xbps-|g' tests/xbps/*/*.sh
```
> fix some some memory leaks

- bin/xbps-install/fetch_cb.c
- include/xbps.h.in
- lib/fetch/ftp.c
- lib/initend.c
I know it's mentioned in the README that it was tested on GCC 4.X, but I was curious if it would run on GCC 7 and it didn't :).
I went over the problems the compiler found and tried to solve them. They weren't that many, but some of them were a little bit tricky.
I think some of them are valid complains and possible bugs, but my work here was very naive: With little context of the project as a whole I tried to fix what I saw. I'm sure I missed something in the process, so excuse me in advance for that.
I separated every file in one commit in which I tried to explain the context of it.
Here is the version of my compiler:
```
$ gcc --version
gcc (GCC) 7.1.1 20170630
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO …
```
> Fix compilation errors on GCC 7

- configure
Fix the test for vasprintf function which failed with musl libc and
fortify-headers on aarch64:
````
_vasprintf.c:4:24: error: incompatible type for argument 3 of 'vasprintf'
vasprintf(NULL, NULL, NULL);
^~~~
````
> configure: fix vasprintf test

- lib/package_unpack.c
- lib/pkgdb.c
- lib/repo_sync.c
`xbps_dictionary_externalize_to_file` uses `_prop_object_externalize_write_file` [1] which creates a new file, sets the permissions with `fchmod(fd, 0666 & ~myumask)` and then renames the new file to the original filename which then ends up with wrong permissions if the umask is too restrictive.
This should fix #232 and #213.
[1] https://github.com/voidlinux/xbps/blob/0.51/lib/portableproplib/prop_object.c#L816
> Fix pkgdb and files plist permissions with restictive umask.

- bin/xbps-uchroot/main.c
- bin/xbps-uunshare/main.c
This fixes #203 and #204 for `xbps-uchroot` and `xbps-uunshare`.
Not sure if it should support `.` to use the current directory as chrootdir and if there should be more error checks to make sure the chrootdir exists.
> xbps-uchroot and xbps-uunshare usability improvements

- bin/xbps-alternatives/xbps-alternatives.1
- bin/xbps-checkvers/xbps-checkvers.1
- bin/xbps-dgraph/xbps-dgraph.1
- bin/xbps-install/xbps-install.1
- bin/xbps-pkgdb/xbps-pkgdb.1
- bin/xbps-query/xbps-query.1
- bin/xbps-reconfigure/xbps-reconfigure.1
- bin/xbps-remove/xbps-remove.1
- data/xbps.d.5
'\\/' renders as '' with mdocml.
> manpages: fix invalid escape

- README.md
- configure
xbps is available in the Arch User Repository, but it doesn't build because it is incompatible with openssl 1.1
(It also doesn't build because of using -Werror in production code as part of "stable" releases instead of via CFLAGS on Travis, but that is another story.)
The standard way to fix this is to rely on pkg-config so that users can point PKG_CONFIG_PATH to their openssl-1.0 package or whatever, and fortunately that results in fewer lines of code that is also more robust. :smile:
Fixes #263, you can update the version requirements whenever xbps is updated to work with openssl 1.1
/cc @Vaelatern
> Consistently use pkg-config to find libssl and document the versions required.
